# Theme configuration for a map coverage viewer (sk)

template : base
title    : Norgeskart
mapscript: 
  template  : mapscript
  baselayers:   
    - template: layers/europa
  overlays  : 
    - template: layers/topo2
      visible : 1
    - template: layers/sjo
    - template: layers/dekning/land/m711/papir
    - template: layers/dekning/land/n50/papir
    - template: layers/dekning/land/n50/plast
      visible : 1
    - template: layers/dekning/sjo/hovedkart
    - template: layers/dekning/sjo/havnekart
    - template: layers/dekning/sjo/kystkart
    - template: layers/dekning/sjo/overseilingskart
  center    : 
    template: center/besseggen
  controls  :
    - template: controls/zoom
    - template: controls/navigation
    - template: controls/layerselector
    - template: controls/hashstate

