# Grunnkonfigurasjon til kartutsnittene paa kartverket.no 

template   : base
title      : Norgeskart
includeXDM : true
mapscript:
  template  : mapscript
  baselayers:   
    - template: layers/europa
  overlays  :
    - template: layers/wmts_param
      usetoken: true
      name: Terreng&shy;modell
      layer: toporaster2
      layerGroup: modus
      id: toporaster
      visible: true
      hidefromlayerswitcher: true

    - include: layers/sjo_hovedkart2


    - template: layers/dekning/land/n50
      name: Landkart 1:50000
      id: dekning.plast
      layerGroup: dekning
      url: /json/dekning/land/n50/plast.json
      preferredBackground: toporaster
      visible: 1

#    - include: layers/dekning_n50_plast
#    - include: layers/dekning_n50_papir
    - include: layers/dekning_sjo_hovedkart
    - include: layers/dekning_havnekart
    - include: layers/dekning_kystkart
    - include: layers/dekning_overseilingskart

  center    : 
    template: center/besseggen
  functions :
  controls  :
    - template: controls/navigation

