template : base
filename : produktvelger.html
title    : Norgeskart
includeXDM : true
mapscript: clients/produktvelger.min.js
---
template : mapscript
filename : clients/produktvelger.min.js
language  : nb
tokenServiceUrl: //www.norgeskart.no/ws/gkt.py
ticketServiceUrl: //www.norgeskart.no/ws/esk.py?wms.ecc_enc
projection: 32633
  
baselayers:   
    - template: layers/europa
overlays  :
    - template: layers/wmts
      usetoken: true
      name: Terreng&shy;modell
      layer: toporaster2
      layerGroup: modus
      id: toporaster
      visible: true
      hidefromlayerswitcher: true

    - include: layers/sjo_hovedkart2


    - template: layers/dekning/land/n50
      name: Landkart 1:50000
      id: dekning.plast
      layerGroup: dekning
      url: /json/dekning/land/n50/pod-inndeling2015-flaterl.json
      preferredBackground: toporaster
      visible: 1

    - include: layers/dekning_sjo_hovedkart
    - include: layers/dekning_havnekart
    - include: layers/dekning_kystkart
    - include: layers/dekning_overseilingskart

center    : 
    template: center/besseggen
functions :
controls  :
    - template: controls/navigation
    - include: toolbars/embed-basic-toolbar

