doc:
  description: i18n for strings used in the base client script

template: i18n/language
language: nb
translations:
  - template: i18n/translation
    source: Server error
    translation: Feil med tjenesten
  - template: i18n/translation
    source: An error has occured.
    translation: Ett eller flere kartlag vises ikke som de skal.
  - template: i18n/translation
    source: Reloading maps in 
    translation: Pr&oslash;ver &aring; laste kartlagene p&aring; nytt om 
  - template: i18n/translation
    source: minutes.
    translation: minutter. 
  - template: i18n/translation
    source: minute.
    translation: minutt. 
  - template: i18n/translation
    source: Visible overlays
    translation: Synlige kartlag
  - template: i18n/translation
    source: Background layers
    translation: Bakgrunnslag
  - template: i18n/translation
    source: Available overlays
    translation: Tilgjengelige kartlag
  - template: i18n/translation
    source: Tools 
    translation: Verkt&oslash;y
  - template: i18n/translation
    source: no attribution 
    translation: uten kildehenvisning
  - template: i18n/translation
    source: about 
    translation: info 
  - template: i18n/translation
    source: Done
    translation: Lukk
